name: CTF-Core
main: org.cwresports.ctfcore.CTFCore
version: 1.1.0-Enhanced
api-version: 1.21
description: Complete Capture the Flag gamemode for Paper 1.21+ with enhanced features
author: CWR Esports
website: https://github.com/cwresports/ctf-core

depend: []
softdepend: [WorldGuard, WorldEdit, PlaceholderAPI, Vault, DecentHolograms]

commands:
  ctf:
    description: Main CTF player command
    usage: /ctf <join|leave|stats|help>
    permission: ctf.play
    permission-message: You don't have permission to use CTF commands
  ctfadmin:
    description: CTF admin commands
    usage: /ctfadmin <create|delete|enable|disable|setup|help>
    permission: ctf.admin
    permission-message: You don't have permission to use CTF admin commands

permissions:
  ctf.*:
    description: All CTF permissions
    default: op
    children:
      ctf.play: true
      ctf.admin: true
  ctf.play:
    description: Allow playing CTF games
    default: true
  ctf.admin:
    description: Allow CTF administration
    default: op
  ctf.join:
    description: Allow joining games
    default: true
    children:
      ctf.play: true
  ctf.leave:
    description: Allow leaving games
    default: true
    children:
      ctf.play: true
  ctf.stats:
    description: Allow viewing statistics
    default: true
    children:
      ctf.play: true